name: Build On PR

<<<<<<< HEAD
On:
  pull_request:
=======
on:
   pull_request:
>>>>>>> 654aa9a4cf4d903793450f20d6377928987023b2
     branches:
      - master
      - main
      - shascodes

jobs: 
  Build: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Use Node.jobs
       uses: actions/setup-node@v3
       with:
        node-version: "20"
     - name: Install Dependencies
       run: npm install
      
     - name: Generate Prisma client
       run: npm run db:Generate
     
     - name: Run build 
       run : npm run build
    
